services:
  app:
    build: .
    image: bucket-adapter:latest
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./bi1-julien.json:/app/bi1-julien.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/bi1-julien.json
      SERVER_PORT: ${SERVER_PORT:-8080}
