spring.application.name=bucket-adapter
spring.config.import=optional:file:.env[.properties]
# TODO NGY Are you mixing Docker and classic config ?
server.port=${SEREVER_PORT:8080}
app.provider-implement=${PROVIDER_IMPL}
aws.region=eu-west-1xwxw