spring.application.name=bucket-adapter
spring.config.import=optional:file:.env[.properties]
server.port=${SEREVER_PORT}
app.provider-implement=${PROVIDER_IMPL}
aws.region=eu-west-1xwxw
server.servlet.context-path=/api